### ISSUE TITLE
Problem 4.14

### ISSUE THREAD

**Issue by sharov-am** [niuers/Learn-From-Data-A-Short-Course#2]
Hi. Thank you very much for your job and solutions, tremendously helpful.
But I have problem to understand your explanation for problem 4.14 a) , namely E_eps(Ein)) you treat as estimate for E_out, but I think this is wrong, E_val could be treated as estimate of E_out. E_eps(Ein)) could estimate average performance on **training** data, but we can't say anything about unseen data.

What do you think?

**Comment by niuers** [comment]
Hi, thanks for looking into the solutions. I guess it's not accurate to say E_eps(Ein) as an estimate of E_out. Wanted to say the sigma term has a coefficient of 1 without overfitting penalty. Any idea how shall we express this?

**Comment by sharov-am** [comment]
Hi. Sorry for delay. I think that you were right -- after all what is E_in if not estimate of E_out? Moreover we are told that overfit no noise, hence I guess we should come up with smth like formula on p. 125, namely E_D(E_out) = sigma^2+bias+var, where given no noise overfit Ithink we can put var=0, hence E_D(E_out) = sigma^2+bias. So, I think that in the absence of noise overfit it is correct to say that E_eps(Ein)) is estimate for E_out. Btw, I'm not sure that in case of no noise overfit we can say that formula on p. 125 has var=0...

PS: In excercise 4.16 b) you have small typo in next to last line -- redundant Z, you have 4 of them instead of 3.

**Comment by niuers** [comment]
Nice discussion and thanks for pointing out the typo, it's fixed now.
