### ISSUE TITLE
4.27 (c) the conservative one-sigma approach and  lambda

### ISSUE THREAD

**Issue by sharov-am** [niuers/Learn-From-Data-A-Short-Course#3]
Hi.

The question is about 4.27(c) and your conclusion in the end and also code.
You state that "We see that the conservative one-sigma approach usually will select the minimum lambda (from all lambdas) as the optimal lambda. ..." and also in code:

`for idx in np.arange(min_idx1+1):
        current_Ecv = E_cvs[idx]
        if current_Ecv >= lb and current_Ecv <= ub:
            min_idx2 = idx
            break` 

But according to the book, we should select the simplest model, hence maximum lambda within given interval (one-sigma), hence
it seems more correctly to write:
`for idx in np.arange(min_idx1+1,len(lambda_ts)):
....`

Also question about (b) part -- why we write strict equality (=) rather then $\approx$ as in part (a)? Equality in part (b) should also contain $\approx$ .

Thank you once again for your work, really very very helpful.

**Comment by niuers** [comment]
Good point, it does seem that we should pick the largest lambda whenever possible using the one-sigma approach. Thanks very much for taking a close look at the code!
please let me know if you see any other problems.

**Comment by sharov-am** [comment]
Thank you for reply. And what is your thoughts  about strict equality in question b)? Is it typo in a book?

**Comment by niuers** [comment]
Might be. Not a big deal to me. I changed to use approximation
