### ISSUE TITLE
Execrise 5.* issues

### ISSUE THREAD

**Issue by sharov-am** [niuers/Learn-From-Data-A-Short-Course#4]
Hi.

Found some issues in your 5.* solutions:

5.1:
a) We need to select 1 from 2^10 options, namely it will define function that for some given input it will output 1 and other will be 0. Hence $|H_{1}|$ = choose 1 from  2^10. Same for   $|H_{100}|$=choose 100 from  2^10. So any realization of 100 from 2^10 defines some function in $|H_{100}|$.
b-c) We need 10 bits to define $|H_{1}|$ because we can define this fucntion with argument which calcultes to 1 (for each fn in  $|H_{1}|$ there will be only one such argument). Same for $|H_{100}|$ -- we need 10*100 bits to define fucntion (hypothesis), naemly encode all it's arguments which calculates to 1.  Here is solution I agree with(math can be well understood) -- https://github.com/Doraemonzzz/Learning-from-data/blob/master/Chapter5/Chapter5%20Three%20Learning%20Principles.pdf (also this solution has small typo for number of hyp. in  $|H_{100}|$)

5.2:
d-e)arithmetic typo in d)

5.3:

> The sampling bias might be caused by the size of the holes on the net. The fish that are **bigger** than the holes are not in the samples.

Maybe smaller fish? We biased towards biag fish.

5.5:
a) I agree with link above, M = 3*500 = 1500

Again, thank you very much for your work.

**Comment by niuers** [comment]
Hi,
  Thanks very much for your comments.
5.1
(a) You are correct, the answer should be just $2^{10}$ and choose 100 from $2^{10}$. I had a $N$ in my formula, which should equal to $2^{10}$, and the final answer evaluate to the same as your answer though. 
(b) You are correct. My answer still refers to how many combinations, not how many bits needed.

5.2: You are correct.

5.3: Should be smaller

5.5 (a): You are correct.

Thanks for pointing them out, very helpful.

**Comment by niuers** [comment]
Fixed
